import Head from "next/head";
import MarketingNav from "~/components/marketing-nav";
import {
  RiLockPasswordFill,
  RiFileTextFill,
  RiBankFill,
  RiBankCardFill,
  RiStickyNoteFill,
} from "react-icons/ri";
import { FaAddressBook } from "react-icons/fa";
import Link from "next/link";
import { Button, buttonVariants } from "~/components/ui/button";
import { cn } from "@/lib/utils";
import SiteFooter from "~/components/site-footer";
import { signIn, useSession } from "next-auth/react";

const features = [
  {
    name: "Logins",
    description:
      "Store and manage login credentials for your various online accounts.",
    Icon: RiLockPasswordFill,
  },
  {
    name: "Files",
    description: "Safely upload and organize files of any format.",
    Icon: RiFileTextFill,
  },
  {
    name: "Bank Accounts",
    description: "Manage your banking information in one place.",
    Icon: RiBankFill,
  },
  {
    name: "Cards",
    description:
      "Safeguard your credit card information for quick and secure access.",
    Icon: RiBankCardFill,
  },
  {
    name: "Secure Notes",
    description: "Keep confidential notes and information protected.",
    Icon: RiStickyNoteFill,
  },
  {
    name: "Addresses",
    description:
      "Store important addresses for quick reference and easy retrieval.",
    Icon: FaAddressBook,
  },
];

export default function Home() {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MarketingNav session={session} />

      <section className="space-y-6 pb-8 pt-6 md:pb-12 md:pt-10 lg:py-32">
        <div className="container flex max-w-[64rem] flex-col items-center gap-4 text-center">
          <Link
            href={"https://github.com/dillontownsend/vault-drop"}
            className="rounded-2xl bg-muted px-4 py-1.5 text-sm font-medium"
            target="_blank"
          >
            Follow along on Github
          </Link>
          <h1 className="font-heading text-3xl font-semibold tracking-tight sm:text-5xl md:text-6xl lg:text-7xl">
            The ultimate digital fortress for your sensitive information
          </h1>
          <p className="max-w-[42rem] font-light leading-normal text-muted-foreground sm:text-xl sm:leading-8">
            Safeguard your login credentials, financial data, and files with
            state-of-the-art encryption, ensuring maximum security and peace of
            mind.
          </p>
          <div className="space-x-4">
            {session ? (
              <Button className={cn(buttonVariants({ size: "lg" }))} asChild>
                <Link href={"/vault"}>Open Vault</Link>
              </Button>
            ) : (
              <Button
                className={cn(buttonVariants({ size: "lg" }))}
                onClick={() =>
                  void signIn("google", {
                    callbackUrl: "/vault",
                  })
                }
              >
                Get Started
              </Button>
            )}
            <Link
              href={"https://github.com/dillontownsend/vault-drop"}
              target="_blank"
              rel="noreferrer"
              className={cn(buttonVariants({ variant: "outline", size: "lg" }))}
            >
              GitHub
            </Link>
          </div>
        </div>
      </section>

      <section
        id="features"
        className="container space-y-6 bg-slate-50 py-8 tracking-tight dark:bg-transparent md:py-12 lg:py-24"
      >
        <div className="mx-auto flex max-w-[58rem] flex-col items-center space-y-4 text-center">
          <h2 className="font-heading text-3xl font-semibold leading-[1.1] sm:text-3xl md:text-6xl">
            Features
          </h2>
          <p className="max-w-[85%] font-light leading-normal text-muted-foreground sm:text-lg sm:leading-7">
            VaultDrop empowers you to securely store and manage a wide range of
            sensitive information all within a single, fortified platform.
          </p>
        </div>
        <div className="mx-auto grid justify-center gap-4 sm:grid-cols-2 md:max-w-[64rem] md:grid-cols-3">
          {features.map((feature) => (
            <div
              key={feature.name}
              className="relative overflow-hidden rounded-lg border bg-background p-2"
            >
              <div className="flex h-[180px] flex-col justify-between rounded-md p-6">
                <feature.Icon className="h-12 w-12 fill-current" />
                <div className="space-y-2">
                  <h3 className="font-bold">{feature.name}</h3>
                  <p className="text-sm text-muted-foreground">
                    {feature.description}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
        <div className="mx-auto text-center md:max-w-[58rem]">
          <p className="font-light leading-normal text-muted-foreground sm:text-lg sm:leading-7">
            VaultDrop also includes an intuitive folder feature, allowing you to
            effortlessly organize and categorize your stored information.
          </p>
        </div>
      </section>

      <section id="open-source" className="container py-8 md:py-12 lg:py-24">
        <div className="mx-auto flex max-w-[58rem] flex-col items-center justify-center gap-4 text-center">
          <h2 className="font-heading text-3xl font-semibold leading-[1.1] tracking-tight sm:text-3xl md:text-6xl">
            Proudly Open Source
          </h2>
          <p className="max-w-[85%] font-light leading-normal text-muted-foreground sm:text-lg sm:leading-7">
            VaultDrop is open source and powered by open source software. <br />{" "}
            The code is available on{" "}
            <Link
              href={"https://github.com/dillontownsend/vault-drop"}
              target="_blank"
              rel="noreferrer"
              className="underline underline-offset-4"
            >
              GitHub
            </Link>
            .{" "}
          </p>
        </div>
      </section>

      <SiteFooter />
    </>
  );
}
